### ISSUE TITLE
MAME Hooker 'Dll Error 6' Issue when exiting after DemulShooter

### ISSUE THREAD

**Issue by phantomsixthplayer** [argonlefou/DemulShooter#158] opened 2023-08-13 16:32 UTC
Edit: The below issue isn't present with the public available [MAME Hooker](http://dragonking.arcadecontrols.com/static.php?page=aboutmamehooker). However, this version of MAME Hooker does not work with the Ultimarc Ultimate I/O, I can provide you the two files to see if you can make support for it?

Issue:
When exiting MAME Hooker after DemulShooter MAME Hooker gives the error "Dll Error 6"
Also, when exiting MAME Hooker after DemulShooter and TeknoParrot have closed MAME Hooker gives the this error "Dll Error 6".
Might this be because MAME Hooker isn't registering the close of DemulShooter properly? Issue does not occur when using the MAME emulator.

Does not occur if I disable DemulShooter Outputs.

Game Tested: Elevator Action Death Parade (might be all DemulShooter games with output enabled)
Software: TeknoParrot, DemulShooter, MAME Hooker (requires a modified mamehook.exe and PacDrive32.dll to work with the Ultimate I/O board)
LED Hardware: Ultimarc Ultimate I/O

Steps to reproduce the issue:
1. Open MAME Hooker
2. Open DemulShooter
3. Open the game from TeknoParrot
4. Exit MAME Hooker

![image](https://github.com/argonlefou/DemulShooter/assets/22541984/64d14c6f-a86b-4ad2-9f95-71d08c4abea1)

https://github.com/argonlefou/DemulShooter/assets/22541984/8a86d56a-55e8-4078-bb6e-1e738a55bf1c

https://github.com/argonlefou/DemulShooter/assets/22541984/b5b46126-edf8-4843-a93d-e5e5bf708e8f

Steps to not reproduce the issue:
1. Open MAME Hooker
2. Open DemulShooter
3. Open the game from TeknoParrot
4. Maximise MAME Hooker go to SysTray -> Test -> Exit
5. Exit MAME Hooker

Steps to not reproduce the issue using the MAME emulator:
1. Open MAME Hooker
2. Open MAME and open a game
3. Exit the game
4. Exit MAME
5. Exit MAME Hooker

Steps to not reproduce the issue using the MAME Hooker and DemulShooter with Outputs Disabled:
1. Open MAME Hooker
2. Open DemulShooter
3. Open the game from TeknoParrot
4. Exit MAME Hooker

MAME Hooker game setting:
`[General]
MameStart=ulk 1
MameStop=ulk 1
StateChange=
OnRotate=
OnPause=
[KeyStates]
RefreshTime=
[Output]
LmpSide_R=
LmpSide_G=
LmpSide_B=
LmpUpBtn=uls 1 2 %s%
LmpDownBtn=
LmpCloseBtn=
P1_GunMotor=
P2_GunMotor=
P1_Ammo=
P2_Ammo=
P1_CtmRecoil=
P2_CtmRecoil=
P1_Life=
P2_Life=
P1_Damaged=
P2_Damaged=
`

Thanks

**Comment by argonlefou** [comment] 2023-08-14 05:40
Hello, thanks for the detailed ticket.

I never ran i to any error using the public version of MameHooker, which is the only one I got.

So yes, I would need your modified version to test. 
Knowing that I have no documentation at all about MameHooker and that I only tried to reproduced what I found in Mame source code....based on what was modified with your dll it may be impossible to know what is happening on my side

**Comment by phantomsixthplayer** [comment] 2023-08-14 09:38
I tried on another Windows 10 PC and got the same messages.
![image](https://github.com/argonlefou/DemulShooter/assets/22541984/11c9522b-8be1-4be0-92ef-a776208c919b)

**Comment by argonlefou** [comment] 2023-08-16 08:27
I got your modded MameHooker file

I'll have a look at it

**Comment by argonlefou** [comment] 2023-08-17 09:27
> Steps to reproduce the issue:
> 
>     1. Open MAME Hooker
> 
>     2. Open DemulShooter
> 
>     3. Open the game from TeknoParrot
> 
>     4. Exit MAME Hooker

So I followed the exact same procedure with TP + Elevator Action, and MameHooker is closing without any error message.
Tried with a few other games too, it's working as good as the "original public" MameHooker version

The only difference I can imagine, is that I don't have any Ultimarc Ultimate I/O device to plug to the computer and so MameHooker is not using that to work during gameplay (which could cause a buggy dll closure maybe ?)

Did you try with an empty MameHooker game ini file ? (at least without any command to hook Ultimarc Ultimate I/O) ?

**Comment by phantomsixthplayer** [comment] 2023-08-17 12:08
Thanks for testing, it seems the issue is when a command is added to an output that changes state. I wonder if something in the ESC process isn't reaching MAME Hooker, because if I run the Test in MAME Hooker after returning from a game it seems the messaging system is sending another exit command to allow for test commands.

1. Connect Ultimarc I/O
2. Open MAME Hooker with empty eadp.ini, open DemulShooter, open game
3. Esc game, Exit MAME Hooker
4. No issue
5. Add command to eadp.ini MameStart to kill all Ultimarc LEDs
6. Open MAME Hooker, open DemulShooter, open game
7. Esc game, Exit MAME Hooker
8. No issue
9. Add command to eadp.ini LmpUpBtn= to set state of Ultimarc LEDs
10. Open MAME Hooker, open DemulShooter, open game
11. Esc game, Exit MAME Hooker
12. DLL Error 6
13. Open MAME Hooker, open DemulShooter, open game
14. Esc game
15. Go to MAME Hooker Test
16. Exit MAME Hooker
17. No issue

Video: https://mega.nz/file/BpIhXALa#lUOPl73S9TgL6zfopxzTQ222CwjNFHq1z2s6QbZPVvQ

**Comment by argonlefou** [comment] 2023-08-17 13:25
The tests I've done in my last reply were with non-empty ini files : but they do only contain serial commands to Gun4IR gun (recoil and rumble).

So this seem to narrow down the issue to the very use of the Ultimarc I/O board commands.
I don't know if you have any other device you can control with MameHooker (gun4ir ?) but it would be nice to be able to test if the error message is still coming if you're using MameHooker with non-empty ini file to control something else than your LEDs

**Comment by phantomsixthplayer** [comment] 2023-08-17 15:20
I'll try another game and see what happens, just trying to think what is different to the MAME emulator for it to work.

[Debug_2023-08-18_01-14-03.txt](https://github.com/argonlefou/DemulShooter/files/12371083/Debug_2023-08-18_01-14-03.txt)
[MAME_Hooker_log.txt](https://github.com/argonlefou/DemulShooter/files/12371086/MAME_Hooker_log.txt)

**Comment by argonlefou** [comment] 2023-08-17 16:23
> Just tested GUN4IR by itself and no issue, then tried GUN4IR with Ultimarc I/O and issue.
> 

So this confirming that the issue is caused by the use of ultimark i/o dll coming with this non-official version of MameHooker.
No need to check with other games or any other setup....if it is crashing because of some unfinished business between mamehooker and the dll at the time you want to exit, it will happen anyways.
We found the "what"

Now....for the "why".... I'm affraid I won't be able to dig more as I do not own that ultimark board and there is no way for me to reproduce that error.
Based

**Comment by argonlefou** [comment] 2023-10-13 12:12
Fixed in v11.2 release

**Closed by argonlefou** 2023-10-13 12:12 UTC

**Comment by Cheesmaker** [comment] 2023-11-13 18:26
It's not a great place for this but could someone share this mamehook.exe and pacdrive32.dll version. I'm on complex stuff with mamehook and I want to try this version wich could have a better support of nanoled by exemple (I do test for boomslangz outputblaster.dll)  Thanks
