### ISSUE TITLE
Operation Wolf Returns Hooking Problem

### ISSUE THREAD

**Issue by megashub** [argonlefou/DemulShooter#216] opened 2024-06-16 17:35 UTC
Followed the wiki instructions. DS hooks successfully at first, but then exits once OperationWolf.exe exits and it launches OperationWolfXR.exe. I think OperationWolf.exe is acting as a launcher so it only survives a brief time. DS hooks fine onto the launcher, but doesn't survive and hook onto OperationWolfXR.exe.

Ran DS in debug mode to aid in troubleshooting:

```
10:46:20.662156 : Found a window : Handle = 0x0027004E, Title = Operation Wolf Returns: First Mission
10:46:20.662156 : => Selecting 0x0027004E as game Window Handle
10:46:20.662156 : Attached to Process OperationWolf.exe, ProcessHandle = 860
10:46:20.662156 : OperationWolf.exe = 0x00007FF640E00000
10:46:20.665148 : MainWindowHandle = 0x0000000000000000
10:46:20.665148 : MainWindowTitle
10:46:20.672150 : MD5 hash of D:\Steam\steamapps\common\Operation Wolf\OperationWolf_Data\Managed\Assembly-CSharp.dll = 3c2de867526e7c281ce75e1cb724589a
10:46:20.673128 : /!\ MD5 Hash unknown, DemulShooter may not work correctly with this target /!\
10:46:20.894537 : Successfully Started DsTcp_Client Listener() Thread
10:46:21.407947 : Ds_TcpClient.Listener(): Successfully connected to 127.0.0.1:33610
10:46:26.707420 : OperationWolf.exe closed
10:46:26.709447 : Cleaning things before exiting application...
``` 

I tried running OperationWolfXR.exe directly instead of OperationWolf.exe after running DS, but OperationWolfXR.exe just runs OperationWolf.exe first anyway, so there's no change in DS behavior with that method either.

Finally, as a last ditch effort, I tried renaming OperationWolfXR.exe to OperationWolf.exe (and just backing up the original), but it fails to run as it expects OperationXR.exe to exist and it doesn't. Didn't think it'd work, but it was worth a shot.

Anyway, let me know if I can provide any other information. 

The game's Build ID in Steam, in case that's valuable information, is 12197373, Installed content updated: Nov 26, 2023

**Comment by megashub** [comment] 2024-06-16 18:17
Update: My problem was that I was not running the game with the right option set. Recommend updating wiki to ensure people launch the game in non-VR mode, either by setting it inside Steam, or via commandline using steam://launch/1852650/option2

**Comment by argonlefou** [comment] 2024-06-16 19:25
Hello,
I was just about to ask if you were trying the VR mode !

I'll update the wiki thanks to your message.
Owning the GOG version of the game, I don't have those options to set the 2D/3D mode because both exe can be run with different results.

As for the initial issue of DS closing, it's an expected behaviour as it will close itself once the hooked process is closed.
Again, using the GOG version I never had this "launcher alike" issue of an exe closing to run another one.

Thanks for the update

**Closed by argonlefou** 2024-06-16 19:25 UTC
