### ISSUE TITLE
Jurassic Park support?

### ISSUE THREAD

**Issue by bdiederichs** [argonlefou/DemulShooter#189] opened 2024-01-06 17:22 UTC
very excited to see 11.5 added JP output support.
But there is no mention of it in the help file or in the wiki at this time.
I tried target rawthrill and rom jp but it didn't hook

is the rom name something else?

**Comment by brewernerd** [comment] 2024-01-06 17:24
I can confirm it did hook for me with the jpark rom name.  Make sure you are using the right demuleshooter exe?

**Comment by bdiederichs** [comment] 2024-01-06 17:38
I was trying rom jp
when trying this, DemulShooter won't even launch

I switched the rom to jpark, and demulashooter launches now but doesn't hook
[Debug_2024-01-06_12-32-02.txt](https://github.com/argonlefou/DemulShooter/files/13850595/Debug_2024-01-06_12-32-02.txt)

**Comment by bdiederichs** [comment] 2024-01-06 17:45
And it looks like DemulShooter is trying to hook Aliens Armageddon
![image0](https://github.com/argonlefou/DemulShooter/assets/51822791/7042f367-41bf-4fda-bc40-1c93a89b7fdd)

**Comment by brewernerd** [comment] 2024-01-06 17:47
Where did it create your jpark.ini? I noticed it dropped mine in the MAME folder inside demulshooter and since it was working I left it in there?

**Comment by bdiederichs** [comment] 2024-01-06 17:49
it doesn't create a jpark.ini

when I launch demulshooter target rawthril rom jpark, my mamehooker aa.ini becomes active but demulshooter itself doesn't hook

**Comment by brewernerd** [comment] 2024-01-06 17:52
Huh, when I did it, I put it debug mode, set mamehooker to hook, ran jpark to snipe outputs, closed the game then selected edit current game ini and it made jpark.ini

**Comment by bdiederichs** [comment] 2024-01-06 18:00
My bad!!!

I was looking under rawthril ...since this is a Raw Thrills game LoL

but it's under target=lindbergh 

Thanks for pointing me to this, brewernerd

**Comment by bdiederichs** [comment] 2024-01-06 18:07
I am getting good outputs for Ammo Life and Damaged
but no recoil.

hopefully custom outputs get added
I'm bridging the gap with keystates and joytokey for now

**Comment by brewernerd** [comment] 2024-01-06 20:51
just going to plus 1 on ctmrecoil outputs, mine is outputing 0/1 based on pulling the trigger but the gun seems to ignore it? using P1_CtmRecoil=nll|cmw 3 F0x2x1x
P2_CtmRecoil=nll|cmw 6 F0x2x1x

Thanks!

**Comment by argonlefou** [comment] 2024-01-08 08:43
> My bad!!!
> 
> I was looking under rawthril ...since this is a Raw Thrills game LoL
> 
> but it's under target=lindbergh
> 
> Thanks for pointing me to this, brewernerd

Indeed, I made a mistake by putting the wrong system for the game's command.
I'll change it back to `target=rawthrill` in the next release

The wiki was updated with the release, the Jurassic Park page is [here](https://github.com/argonlefou/DemulShooter/wiki/Lindbergh#jurassic-park)
I'm trying to keep the wiki updated but I may forget some things here and there.

In case of doubt, the only way to be 100% certain of the command to use for a game is simple to run :  
`DemulShooter.exe -h` or `DemulShooterX64.exe -h`


> I am getting good outputs for Ammo Life and Damaged but no recoil.
> 
> hopefully custom outputs get added I'm bridging the gap with keystates and joytokey for now

Custom recoil is already working, synchronized with each weapon's firing rate.
Just use `P1_CtmRecoil` and `P2_CtmRecoil` outputs.

You can also see (summarized) what are the supported outputs for each game [here](https://github.com/argonlefou/DemulShooter/wiki/Outputs) (again, sorry for putting jpark under lindbergh for now)


> just going to plus 1 on ctmrecoil outputs, mine is outputing 0/1 based on pulling the trigger but the gun seems to ignore it? using P1_CtmRecoil=nll|cmw 3 F0x2x1x P2_CtmRecoil=nll|cmw 6 F0x2x1x
> 
> Thanks!

DemulShooter is only providing outputs out of the game. If you can see it changing in MameHooker debug window, you can consider that the job is done for that part.

Now fixing GUN4IR solenoid control and serial commands is not something that can be covered here, you should get a lot of help in the GUN4IR Discord channel.

**Comment by argonlefou** [comment] 2024-02-05 17:32
> My bad!!!
> 
> I was looking under rawthril ...since this is a Raw Thrills game LoL
> 
> but it's under target=lindbergh
> 
> Thanks for pointing me to this, brewernerd

Fixed in v11.6 update, game goes back under `target=rawthrill

**Closed by argonlefou** 2024-02-05 17:32 UTC
